#microk8s enable ingress:default-ssl-certificate=namespace/secret_name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: default
  labels:
    app:  nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:         
      containers:
      - name:  nginx
        image: bitnami/nginx:latest        
        ports:
        - containerPort: 8080
          name:  http
        volumeMounts:           
          - name: nginx-conf-yaml
            mountPath: "/opt/bitnami/nginx/conf/nginx.conf"
            subPath: nginx.conf   
          - name: site-conf-yaml
            mountPath: "/opt/bitnami/nginx/conf/conf.d/site.conf"
            subPath: site.conf          
          - mountPath: /var/log/smarthub/iotc
            name: hostvol1          
      volumes:
        - name: local-path-pvc
          persistentVolumeClaim: 
            claimName: local-nginx-pvc        
        - configMap:            
            name: nginx-conf-yaml
          name: nginx-conf-yaml
        - configMap:            
            name: site-conf-yaml
          name: site-conf-yaml        
        - name: hostvol1
          hostPath:
            path: /home/kranti/nk275/nginx/nginx/logs           
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-nginx-pvc
#  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 2Gi    
      
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  type: ClusterIP 
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
